version: '3.1'
services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis_db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/footytipper
      - PORT=5000
      - REDIS_URL=redis://redis_db:6379
  db:
    image: postgres
    environment:
      - POSTGRES_DB=footytipper
  redis_db:
    image: redis
