"""empty message

Revision ID: 4d4bdfdb74c7
Revises: 9ecff1ca6117
Create Date: 2018-01-21 10:40:39.343681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d4bdfdb74c7'
down_revision = '9ecff1ca6117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betting_odds', sa.Column('point_spread', sa.Integer(), nullable=True))
    op.add_column('betting_odds', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('betting_odds', sa.Column('win_odds', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'betting_odds', 'teams', ['team_id'], ['id'])
    op.drop_column('betting_odds', 'away_point_spread')
    op.drop_column('betting_odds', 'home_point_spread')
    op.drop_column('betting_odds', 'home_win_odds')
    op.drop_column('betting_odds', 'away_win_odds')
    op.add_column('matches', sa.Column('away_betting_odds_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('home_betting_odds_id', sa.Integer(), nullable=True))
    op.drop_constraint('matches_betting_odds_id_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'betting_odds', ['away_betting_odds_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'betting_odds', ['home_betting_odds_id'], ['id'])
    op.drop_column('matches', 'crowd_size')
    op.drop_column('matches', 'betting_odds_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('betting_odds_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('crowd_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_betting_odds_id_fkey', 'matches', 'betting_odds', ['betting_odds_id'], ['id'])
    op.drop_column('matches', 'home_betting_odds_id')
    op.drop_column('matches', 'away_betting_odds_id')
    op.add_column('betting_odds', sa.Column('away_win_odds', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('betting_odds', sa.Column('home_win_odds', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('betting_odds', sa.Column('home_point_spread', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('betting_odds', sa.Column('away_point_spread', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'betting_odds', type_='foreignkey')
    op.drop_column('betting_odds', 'win_odds')
    op.drop_column('betting_odds', 'team_id')
    op.drop_column('betting_odds', 'point_spread')
    # ### end Alembic commands ###
