"""empty message

Revision ID: e9ca74b3266e
Revises: 1429d45ee77c
Create Date: 2018-01-21 13:59:17.495511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ca74b3266e'
down_revision = '1429d45ee77c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('away_betting_odds_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('home_betting_odds_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'betting_odds', ['away_betting_odds_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'betting_odds', ['home_betting_odds_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'home_betting_odds_id')
    op.drop_column('matches', 'away_betting_odds_id')
    # ### end Alembic commands ###
