"""empty message

Revision ID: ecff8fe7e0d4
Revises: 4d4bdfdb74c7
Create Date: 2018-01-21 13:16:46.209082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecff8fe7e0d4'
down_revision = '4d4bdfdb74c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betting_odds', sa.Column('away_match_id', sa.Integer(), nullable=True))
    op.add_column('betting_odds', sa.Column('home_match_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'betting_odds', 'matches', ['away_match_id'], ['id'])
    op.create_foreign_key(None, 'betting_odds', 'matches', ['home_match_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'betting_odds', type_='foreignkey')
    op.drop_constraint(None, 'betting_odds', type_='foreignkey')
    op.drop_column('betting_odds', 'home_match_id')
    op.drop_column('betting_odds', 'away_match_id')
    # ### end Alembic commands ###
